- name: Fetch CRAN repository key
  become: yes
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: E084DAB9
    state: present

- name: Add CRAN repository
  become: yes
  apt_repository:
    repo: deb https://cloud.r-project.org/bin/linux/ubuntu trusty/
    state: present

- name: Install R packages
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - libcurl4-gnutls-dev
    - r-base

- name: R packages | install
  become: yes
  command: >-
    Rscript --slave --no-save --no-restore-history -e
    "if(!('{{ item }}' %in% installed.packages())) { install.packages('{{ item }}', repos='http://cran.rstudio.com') }"
  with_items:
    - shiny
    - jsonlite
    - pheatmap
    - survival
    - igraph
    - cccd

- name: Install Python dependencies for Girder Worker
  command: "{{ storage }}/venv/bin/pip install -r requirements.txt"
  args:
    chdir: "{{ worktree }}/girder_worker"

- name: Install Python dependencies for girder_io plugin
  command: "{{ storage }}/venv/bin/pip install -r requirements.txt"
  args:
    chdir: "{{ worktree }}/girder_worker/girder_worker/plugins/girder_io"

- name: Install Python dependencies for r plugin
  command: "{{ storage }}/venv/bin/pip install -r requirements.txt"
  args:
    chdir: "{{ worktree }}/girder_worker/girder_worker/plugins/r"

- name: Copy local config file for Girder Worker
  copy:
    src: ../../asset/worker.local.cfg
    dest: "{{ worktree }}/girder_worker/girder_worker"

- name: Install Girder Worker in editable mode
  command: "{{ storage }}/venv/bin/pip install -e ."
  args:
    chdir: "{{ worktree }}/girder_worker"

- name: Install Girder Worker service
  become: yes
  template:
    src: ../../asset/girder-worker.upstart.j2
    dest: /etc/init/girder-worker.conf

- name: (Re)start Girder Worker service
  become: yes
  service:
    name: girder-worker
    state: restarted
