- name: Get id for Large.csv
  girder:
    port: 8080
    scheme: http
    username: "{{ adminuser_login }}"
    password: "{{ adminuser_password }}"
    get:
      path: item
      parameters:
        folderId: "{{ sample_data_folder['gc_return'][0]['_id'] }}"
        name: Large.csv
  register: large

- name: Get metadata flags on Large.csv
  girder:
    port: 8080
    scheme: http
    username: "{{ adminuser_login }}"
    password: "{{ adminuser_password }}"
    put:
      path: "item/{{ large['gc_return'][0]['_id'] }}/metadata"
      parameters:
        metadata: '{"sumoDataType":"mrna"}'
