---
- hosts: all
  become_user: root
  become_method: sudo
  vars_files:
    - ../vars.yml

  pre_tasks:
    - include: mongo.yml
    - include: node7.yml
    - name: Update APT keyring
      become: yes
      shell: apt-key update
    - name: Update APT packages
      become: yes
      apt:
        update_cache: yes
    - name: Install APT packages
      become: yes
      apt:
        name:
          - apt-transport-https
          - build-essential
          - git
          - lib32z-dev
          - libffi-dev
          - libjpeg-dev
          - libssl-dev
          - libxml2-dev
          - libxslt1-dev
          - libz-dev
          - nginx
          - nodejs
          - openssl
          - python-dev
          - python-virtualenv
          - wget
          - zlib1g-dev

  roles:
    - role: girder
      girder_path: "{{ worktree }}/girder"
      girder_virtualenv: "{{ girder_venv }}"
      girder_clone: no
      girder_update: no
      girder_force: no

  post_tasks:
    - include: girder-worker.yml
    - include: girder-plugin.yml
    - include: girder-setup.yml
